---
- name: Playbook deploy
  hosts: app_server
  become_method: runas
  become_user: root
  tasks:
    - name: copy war into VM
      win_get_url:
        url: http://192.168.1.16:8081/repository/nexus-repo/in/javahome/dockeransible/1.0-SNAPSHOT/dockeransible-1.0-20220718.052212-43.war
        url_username: admin            
        url_password: admin    
        force_basic_auth: yes
        dest: C:\app_deployment
