---
- name: Playbook deploy
  hosts: app_server
  become_method: runas
  become_user: root
  tasks:
    - name: copy war into VM
      copy:
        src: http://localhost:8081/repository/nexus-repo/in/javahome/dockeransible/1.0-SNAPSHOT/dockeransible-1.0-20220704.183055-1.war
        dest: C:\app-deployment
