---
- name: Playbook deploy
  hosts: app_server
  become_method: runas
  become_user: root
  tasks:
    - name: copy war into VM
      win_copy:
        remote_src: http://localhost:8081/repository/nexus-repo/in/javahome/dockeransible/1.0-SNAPSHOT/dockeransible-1.0-20220704.183055-1.war
        user: "{{ admin }}"            
        password: "{{ admin }}"    
        force_basic_auth: yes
        dest: C:\app-deployment
